### ISSUE TITLE
ida 6.8 uses db.get.string() to get an error:

### ISSUE THREAD

**Issue by gool123456** [arizvisa/ida-minsc#120]
Hi, @arizvisa , ida 6.8 uses db.get.string() to get an error:

Python>db.get.string()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 341, in database.string
    return f(*arguments, **keywords)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 5968, in string
    return cls.string(ui.current.address(), **length)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 341, in database.string
    return f(*arguments, **keywords)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 6084, in string
    res = cls.array(ea + shift, **length).tostring()
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 341, in database.array
    return f(*arguments, **keywords)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 5933, in array
    return decode_array(ea, T, length['length'], numerics, lnumerics)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 5849, in decode_array
    if _instruction.ops_refinfo(ea) or F & idaapi.FF_SIGN:
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 341, in instruction.ops_refinfo
    return f(*arguments, **keywords)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\instruction.py", line 1086, in ops_refinfo
    return op_refinfo(ea, OPND_ALL)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 341, in instruction.op_refinfo
    return f(*arguments, **keywords)
  File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\instruction.py", line 1095, in op_refinfo
    return ri if idaapi.get_refinfo(ri, ea, opnum) else None
  File "D:\tools\IDA_Pro_v6.8_and_Hex-Rays_Decompiler_(ARM,x64,x86)_Hskyre\python\idaapi.py", line 6938, in get_refinfo
    return _idaapi.get_refinfo(*args)
TypeError: Expected an ea_t type

**Comment by gool123456** [comment]
I am using the latest package

**Comment by arizvisa** [comment]
Hi @gool123456, can you try PR #121 and see if that fixes it for you?

**Comment by gool123456** [comment]
@arizvisa Ok, It's already normal. Thanks :-)

**Comment by arizvisa** [comment]
So, that fixed it?

**Comment by gool123456** [comment]
> So, that fixed it?

Year, Is fixed !

**Comment by arizvisa** [comment]
Awesome. Thanks, sir!

**Comment by arizvisa** [comment]
Closing this issue as it was fixed by PR #121 which was just merged into the master branch as commit efa43068c9686a00a798dd509de6ceb51df934aa. If you feel this is in error, please let me know and I'll re-open the issue.
