### ISSUE TITLE
enum.members.iterate/list result in exception

### ISSUE THREAD

**Issue by c0d3z3r0** [arizvisa/ida-minsc#151]
IDA Pro 32  v7.6.210427

enum.members.iterate/list result in exception:

~~~
Python>list(enum.members.iterate('REGS'))
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\enumeration.py", line 770, in iterate
    for item in cls.__iterate__(eid):
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\enumeration.py", line 744, in __iterate__
    for bitmask in masks.iterate(eid):
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\enumeration.py", line 1102, in iterate
    eid = by(enum)
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\_utils.py", line 627, in enumeration.by
    return result_callable(*itertools.chain(parameters, wild_parameters), **keyword_parameters)
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\enumeration.py", line 126, in by
    return by_identifier(index) if interface.node.is_identifier(index) else by_index(index)
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\enumeration.py", line 112, in by_index
    raise E.EnumerationNotFoundError(u"{:s}.by_index({:#x}) : Unable to locate the enumeration at index {:d}.".format(__name__, index, index))
internal.exceptions.EnumerationNotFoundError: enumeration.by_index(0x7f039b02) : Unable to locate the enumeration at index 2130942722.
Python>enum.members.list('REGS')
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\enumeration.py", line 779, in list
    listable = [item for item in cls.iterate(eid)]
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\enumeration.py", line 769, in iterate
    eid = by(enum)
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\_utils.py", line 627, in enumeration.by
    return result_callable(*itertools.chain(parameters, wild_parameters), **keyword_parameters)
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\enumeration.py", line 126, in by
    return by_identifier(index) if interface.node.is_identifier(index) else by_index(index)
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\enumeration.py", line 112, in by_index
    raise E.EnumerationNotFoundError(u"{:s}.by_index({:#x}) : Unable to locate the enumeration at index {:d}.".format(__name__, index, index))
internal.exceptions.EnumerationNotFoundError: enumeration.by_index(0x7f039b02) : Unable to locate the enumeration at index 2130942722.
~~~

**Comment by arizvisa** [comment]
Can you do a git-pull and try again? I'm in the middle of doing a refactor for 7.7 because I realized a major issue due to the way that I'm handling identifiers.

**Comment by arizvisa** [comment]
Oh for the record, the reason why your issue happened is because of rebasing the database or a segment moving. I'm not handling the netnodes consistently between versions of IDA which is what I've been fixing in this release. It's been broken in 7.6 because IDA changed the time that they dispatched the event and since I don't ever rebase, I just never noticed it. :-/.

**Comment by c0d3z3r0** [comment]
> Can you do a git-pull and try again? I'm in the middle of doing a release for 7.7 because I realized a major issue due to the way that I'm handling identifiers. So it should fix your enumeration identifier issue. Although you may notice some excessive warnings in the meantime as I'm close to doing a proper release.

Yay, works fine now :+1:

> Btw, sorry that I didn't see this until a week later. There's been a lot of work done with the segment code in minsc as when 7.7 SP1 was released they changed a number of things and busted up the logic for the floating license. so for a while IDA was stuck in a loop until it deref'd a null pointer thus I couldn't dev things.

No worries :-)

> Oh for the record, the reason why your issue happened is because of rebasing the database or a segment moving. I'm not handling the netnodes consistently between versions of IDA which is what I've been fixing in this release. It's been broken in 7.6 because IDA changed the time that they dispatched the event and since I don't ever rebase, I just never noticed it. :-/.

Hmhmmm, I never had tried a non-rebased databse, so yes, that makes sense here

**Comment by arizvisa** [comment]
Btw, I just did a proper release a few minutes ago for 7.7 so if you do a git-pull you'll have the most recent "stable" version.
