### ISSUE TITLE
custom.tagfix.extracomments ERROR

### ISSUE THREAD

**Issue by taodaqiao** [arizvisa/ida-minsc#19]
custom.tagfix.extracomments() ErrorTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Roaming\Hex-Rays\IDA Pro\custom\tagfix.py", line 233, in extracomments
    for ea in db.address.iterate(left, right):
  File "C:\Users\Administrator\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 1740, in iterate
    res = step(res)
  File "C:\Users\Administrator\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 292, in database.next
    return f(*arguments, **keywords)
  File "C:\Users\Administrator\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 1856, in next
    return cls.next(ea, 1)
  File "C:\Users\Administrator\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 292, in database.next
    return f(*arguments, **keywords)
  File "C:\Users\Administrator\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 1866, in next
    return cls.nextF(ea, utils.fidentity, count)
  File "C:\Users\Administrator\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 292, in database.nextF
    return f(*arguments, **keywords)
  File "C:\Users\Administrator\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 1925, in nextF
    raise E.AddressOutOfBoundsError("{:s}.nextF: Refusing to seek past the bottom of the database ({:#x}). Stopped at address {:#x}.".format('.'.join((__name__, cls.__name__)), config.bounds()[1], idaapi.get_item_end(ea)))
AddressOutOfBoundsError: database.address.nextF: Refusing to seek past the bottom of the database (0x41d000). Stopped at address 0x41d000.

**Comment by arizvisa** [comment]
Please triple-backtick code-pastes so that markdown doesn't break your formatting.

But cool. Apparently that was broken by commit e07f273a0966e98a2e9fc348b89b2a461c8672f0 last week. Thanks for the report.

**Comment by arizvisa** [comment]
Should be fixed by commit 653d89c47dafb7d95b106fb4cb6c048d0ab6c18a. Do a `git pull` and you should be good to go.
