### ISSUE TITLE
Unable to list imports against an elf executable with the imports module name is None

### ISSUE THREAD

**Issue by arizvisa** [arizvisa/ida-minsc#27]
When calling `database.imports.list()` with an ELF executable, the module name returned from `database.imports.iterate()` is None which results in the following exception when trying to calculate the length of the module name.

```
Python>db.imports.list()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 292, in database.list
    return f(*arguments, **keywords)
  File "C:\Users\user\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 1754, in list
    @utils.multicase()
  File "C:\Users\user\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 1406, in wrapper
    return F(*res, **kwds)
  File "C:\Users\user\AppData\Roaming\Hex-Rays\IDA Pro\base\database.py", line 1762, in list
    maxmodule = max(builtins.map(utils.fcompose(utils.second, utils.first, len), res) or [''])
  File "C:\Users\user\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 47, in <lambda>
    fcompose = lambda *f: builtins.reduce(lambda f1, f2: lambda *a: f1(f2(*a)), builtins.reversed(f))
  File "C:\Users\user\AppData\Roaming\Hex-Rays\IDA Pro\base\_utils.py", line 47, in <lambda>
    fcompose = lambda *f: builtins.reduce(lambda f1, f2: lambda *a: f1(f2(*a)), builtins.reversed(f))
TypeError: object of type 'NoneType' has no len()
```

Somewhat related, when calling `database.exports.list()` the export address is printed out twice due to the export ordinal for an entrypoint being returned as the export's address. This can probably be cleaned up.

```
Python> db.exports.list()
...
[7] 0x180611c60 : (0x8) IAEModule_IAEKernel_UnloadModule
[8] 0x180a6dce0 : (0x180a6dce0) DllEntryPoint
```

**Comment by arizvisa** [comment]
Closed by PR #28.
