### ISSUE TITLE
Comments don't appear to remain hooked 100% of the time, and some events are missed.

### ISSUE THREAD

**Issue by arizvisa** [arizvisa/ida-minsc#50]
Every once in a while, the hooks for updating the cache when the user changes the comments in a function or the database don't execute. This can result in the cache not being up to date at all times.

Some of the symptoms that appear are that the `ValueError` exception gets raised mentioning that the generator is already executing:

```
CRITICAL:root:internal.interface.priorityhook.callback(4199627, False, 'this') : Callback for "IDB_Hooks.changing_cmt" with priority (+0) raised an exception while executing <bound method type.changing of <class 'hooks.address'>>
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') : Traceback ("IDB_Hooks.changing_cmt" was hooked at)
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') :   File "/home/user/idapro-7.4/python/2/ida_idp.py", line 3792, in dispatch
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') :     cb.fun(slot, *args)
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') :   File "/home/user/work/ida-minsc/base/_interface.py", line 373, in closure
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') :     result = callable(*parameters)
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') :   File "/home/user/work/ida-minsc/misc/hooks.py", line 842, in make_ida_not_suck_cocks
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') :     ui.hook.idb.add('changing_cmt', address.changing, 0)
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') : 
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') : Traceback (most recent call last):
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') :   File "/home/user/work/ida-minsc/base/_interface.py", line 373, in closure
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') :     result = callable(*parameters)
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') :   File "/home/user/work/ida-minsc/misc/hooks.py", line 186, in changing
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') :     try: cls.event.send((ea, bool(repeatable_cmt), utils.string.of(newcmt)))
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') : ValueError: generator already executing
WARNING:root:internal.interface.priorityhook.callback(4199627, False, 'this') : 
```

**Comment by arizvisa** [comment]
This issue is closed by PR #51.
