### ISSUE TITLE
Rebasing a database to a new address results in a number of errors being displayed.

### ISSUE THREAD

**Issue by arizvisa** [arizvisa/ida-minsc#78]
When rebasing the database in IDA 7.5, a bunch of exceptions are logged while executing hooks. Although the rebase is successful, the tag cache is screwed up as it's still pointing to the original locations due to the lack of being transformed.

It seems that the hook is being dispatched after the rebase has happened resulting in the following exception while trying to access an address prior to the rebase.
```
Traceback (most recent call last):
  File "/home/user/work/ida-minsc/base/_interface.py", line 382, in closure
    result = callable(*parameters)
  File "/home/user/work/ida-minsc/misc/hooks.py", line 687, in rename
    fl = database.type.flags(ea)
  File "/home/user/work/ida-minsc/base/_utils.py", line 338, in database.flags
    return f(*arguments, **keywords)
  File "/home/user/work/ida-minsc/base/database.py", line 3132, in flags
    return getflags(interface.address.within(ea))
  File "/home/user/work/ida-minsc/base/_interface.py", line 740, in within
    return cls.__within1__(*args)
  File "/home/user/work/ida-minsc/base/_interface.py", line 720, in __within1__
    raise internal.exceptions.OutOfBoundsError(u"{:s} : The specified address {:#x} is not within the bounds of the database ({:#x}<>{:#x}).".format(entryframe.f_code.co_name, ea, l, r))
OutOfBoundsError: closure : The specified address 0x15008 is not within the bounds of the database (0x400000<>0x419578).
```

The next exception is raised while trying to access the segment info vector. This looks like an off-by-one when accessing it.
```
Traceback (most recent call last):
  File "/home/user/work/ida-minsc/base/_interface.py", line 382, in closure
    result = callable(*parameters)
  File "/home/user/work/ida-minsc/misc/hooks.py", line 600, in rebase
    msg = u"Rebasing tagcache for segment {:d} of {:d} : {:#x} ({:+#x}) -> {:#x}".format(si, scount, info[si]._from, info[si].size, info[si].to)
  File "/home/user/idapro-7.5/python/2/ida_moves.py", line 366, in __getitem__
    return _ida_moves.segm_move_info_vec_t___getitem__(self, *args)
IndexError: out of bounds access
```

**Comment by arizvisa** [comment]
I umm..swear this worked before. (I really hope IDA 7.5 didn't switch the order that the hook is executed...)

**Comment by arizvisa** [comment]
PR #79 fixes this issue.

**Comment by arizvisa** [comment]
Closed because it works dammit.
